- name: remove old docker resource 
  shell: docker rm -f $(docker ps -aq)
  ignore_errors: true
  tags: remove_old_docker

- name: copy docker bin
  copy: src=dockerbin/ dest=/usr/bin/ mode=0755 force=yes
  tags: copydocker

- name: template docker.service to server
  template: src=docker.service dest=/etc/systemd/system/docker.service
  tags: docker

- name: set hostname
  shell: echo dockernode > /etc/hostname && hostname dockernode
  tags: hosts
  
- name: template hosts 
  template: src=hosts dest=/etc/hosts
  tags: hosts

- name: stop load docker
  shell: "kill -9 $(cat /var/run/docker.pid)"
  ignore_errors: true
  tags: docker

- name: start docker
  service: name=docker state=started enabled=yes
  tags: docker
